version: '2'

volumes:
  mysql_data:

services:

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=test123"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./docker/mariadb/mysqlInnodb.cnf:/etc/mysql/conf.d/mysqlInnodb.cnf"
      - "./docker/mariadb/:/docker-entrypoint-initdb.d/"
    ports:
      - "127.0.0.1:3307:3306"